### ISSUE TITLE
Ability to override kpack custom builder

### ISSUE THREAD

**Issue by cmoulliard** [cloudfoundry/cf-for-k8s#178]
## Description of the problem

It is not possible to override the builder image as ytt will fail 

```
ytt: Error: Overlaying data values (in following order: values.yml, cf-values.yml): Document on line cf-values.yml:2: Map item (key 'images') on line cf-values.yml:191: Map item (key 'cf_autodetect_builder') on line cf-values.yml:192: Expected number of matched nodes to be 1, but was 0 if I include within the cf-values.yml file image:  cf_autodetect_builder
```

if we try to include within the generated `cf-values.yml` file the following information

```
images:
   cf_autodetect_builder: my_builder_image
```

## Proposition

We propose to extend the `capi.yml` file in order to add the following `ytt if/end condition` to support to override the `images.cf_autodetect_builder` 

```
#@ if/end data.values.images.cf_autodetect_builder:
  cf_autodetect_builder: #@ data.values.images.cf_autodetect_builder
```

and to include a default value within the `values.yml` file
```
images:
   cf_autodetect_builder: cloudfoundry/cnb:0.0.94-bionic
```

**Comment by cmoulliard** [comment]
Can this issue be reviewed, discussed and perhaps added to the next milestone (v0.3.0) please ?

**Comment by jamespollard8** [comment]
> Can this issue be reviewed, discussed and perhaps added to the next milestone (v0.3.0) please ?

Hey Charles, we actually worked on related kpack configuration with CAPI today and the notes from the work are captured in this story: https://www.pivotaltracker.com/story/show/172559552 (the summary comment is probably the most helpful)

The solution we're planning on taking actually goes further than your request here. We're working towards enabling a custom builder with paketo buildpacks. Unfortunately we're blocked on several things and we don't plan on prioritizing this work in the next few weeks.

**Comment by acosta11** [comment]
Hi Charles,

As an update, we just implemented the paketo buildpacks based custom builder in release v0.4.0 . See https://github.com/cloudfoundry/cf-for-k8s/blob/master/config/default-buildpacks.yml for the specific buildpacks included. I suspect for now the only way to go about configuring these is to write an overlay, since we haven't yet circled back to making the template for that custom builder configurable directly via values.

Thanks,
Andrew

**Comment by cmoulliard** [comment]
I got this error if I try to add the `cf_autodetect_builder` field to my `/tmp/cf_values.yml` file using cf-for-k8s version 0.4.0

```
ytt -f config -f /tmp/cf-values.yml > /tmp/cf-for-k8s-rendered.yml
ytt: Error: Overlaying data values (in following order: values.yml, cf-values.yml):
  Document on line cf-values.yml:2:
    Map item (key 'images') on line cf-values.yml:192:
      Map item (key 'cf_autodetect_builder') on line cf-values.yml:193:
        Expected number of matched nodes to be 1, but was 0
```

Is this syntax still correct ?

```
images:
  cf_autodetect_builder: cmoulliard/paketo-spring-boot-builder@sha256:f0fe222b06fd54e580a1366646f31e7b5b59047c3112b8416c06994e4109cd30
```

**Comment by cppforlife** [comment]
@cmoulliard hey, i'd like to help you make sense of this error:

> ytt is a too complex tool to be used and dont help to understand where error is coming from !!!!!

```
  Document on line cf-values.yml:2:
    Map item (key 'images') on line cf-values.yml:192:
      Map item (key 'cf_autodetect_builder') on line cf-values.yml:193:
        Expected number of matched nodes to be 1, but was 0
```

ytt error messages include line numbers for things ytt cannot figure out. in this snippet it says that `cf_autodetect_builder` (on line cf-values.yml:193) resulted in `Expected number of matched nodes to be 1, but was 0` error. to say it in another words, ytt expected to find `cf_autodetect_builder` key to override, but did not find it, because cf-for-k8s does not offer such configuration.

this can be seen here (https://github.com/cloudfoundry/cf-for-k8s/blob/cbbb55fc592348a19270057e0b37d6bbadfe5824/config/values.yml#L27-L31): `images.*` does not have `cf_autodetect_builder` key that can be set.

(as a side note, in a similar case, helm would have failed silently disregarding that this was not a valid setting.)

i was surprised that you were trying to configure a setting that didnt exist so i looked around a bit more. there is a setting in capi that allows to set this value (https://github.com/cloudfoundry/cf-for-k8s/blob/cbbb55fc592348a19270057e0b37d6bbadfe5824/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values/images.yml). this is effectively an internal setting to capi. ytt v0.28.0+ does allow to set that though...

```yaml
#@data/values
#@library/ref "@github.com/cloudfoundry/capi-k8s-release"
---
images:
  cf_autodetect_builder: "..."
```

let's also dig into what @acosta11 is saying about overlays. overlays allow you to patch cf-for-k8s yaml in any way on top of what cf-for-k8s team decided to expose. as a general practice it's very likely that cf-for-k8s team will not expose 100s of configuration knobs for every single use case out there (a common problem lots of helm chart maintainers mention). with overlays you do not have to rely on cf-for-k8s team to tweak configuration to your desire.

interestingly enough though, it doesnt look like capi configuration uses images.cf_autodetect_builder data value at all so there is nothing to patch via an overlay since resulting yaml does not include it.

**Comment by jamespollard8** [comment]
closing as stale
