### ISSUE TITLE
Expose defaultIdentityProvider for uaa

### ISSUE THREAD

**Issue by jkbschmid** [cloudfoundry/cf-for-k8s#185]
### Summary

In order to transparently use an external identity provider instead of uaa itself, we would like to set

```
login: 
  defaultIdentityProvider: myIdP
```
via uaa-values.
Would you accept a PR that exposes this property? Default could be set to "uaa", so the behavior only changes if the value is actually set.

### Expected behavior

I can do `cf login` using my external identity provider, without specifying `--origin`.

**Comment by reneighbor** [comment]
@jkbschmid Thanks for writing and for your offer of a PR! @jspawar as someone with in-depth UAA and cf-for-k8s knowledge, what do you think?

**Comment by jspawar** [comment]
FWIW, the UAA BOSH release currently defaults that value to null and I'd suspect as a result the UAA team would deliberately like to keep it that way: https://github.com/cloudfoundry/uaa-release/blob/61ef2da61395b296b92033980a3a7a7299866cf1/jobs/uaa/spec#L397-L400

**Comment by kramerul** [comment]
Hi @reneighbor, are there any news on this topic?

**Comment by loewenstein** [comment]
@davewalter @jamespollard8 Would be great to know if this can be considered as an official option or not. If not, I'd be interested to hear if the [overlay we currently have](https://github.com/akhinos/cf-for-k8s-gardener/blob/master/overlays/default-idp.yml) can be considered safe to use.

**Comment by jpalermo** [comment]
Sorry for the delay on this issue. The desired outcome totally makes sense. We've currently got it blocked as we're thinking through how we want users to be able to specify things like this.

The current direction we're headed in would be a values file with hundreds of different flags which is not the surface area we want in cf-for-k8s.

We also have the problem that there are things people want to configure that may not yet be exposed from the component teams, so even if you wanted to just write a custom overlay file, you can't. So we'd like to give component teams guidance on how best to make their components configurable.

We haven't had a chance to really think through good solutions to these two problems, but it's quickly becoming an issue so we'll have to tackle it very soon so we can deal with issues such as this one.

We'd love to hear any input you have on best ways to make the product configurable without creating too big of a surface area.

**Comment by loewenstein** [comment]
> The current direction we're headed in would be a values file with hundreds of different flags which is not the surface area we want in cf-for-k8s.

I totally agree that a vast list of low-level configuration knobs is undesirable. It's probably one of the things Istio is infamous for.

> We also have the problem that there are things people want to configure that may not yet be exposed from the component teams, so even if you wanted to just write a custom overlay file, you can't.

Do you have an example for this? Because you can basically overlay everything with YTT (not sure if I should consider this a good or bad thing though). See for an example the overlay mentioned above, it overlays the uaa configuration that the uaa writes to a ConfigMap and cf-for-k8s has already overlayed once...

> We'd love to hear any input you have on best ways to make the product configurable without creating too big of a surface area.

I'd say cf-for-k8s should provide some standard options via value flags or official overlays. If we would only know already, what we should consider a "standard option" ... ;)

Jokes aside, I think that requiring custom overlays is just fine for the 20% cases. The important thing would be to have at least some level of stability. In this particular, I would ask the component teams to provide configuration API (i.e. config options they are willing to support long-term) and other, less stable options clearly tagged as what they are. Could be separate ConfigMaps or the yaml structure could separate those.

We will have our overlays tested in CI/CD, so hopefully we'll catch incompatible changes and hopefully we'll always find an alternative for the options we want to set.

**Comment by jamespollard8** [comment]
Thanks @loewenstein for the thoughtful response.

You've probably noticed that we've been very careful about which optional-config overlays we've allowed into the repo. Until post GA, we're going stay consistent about keeping custom overlays separate from this repo - we'll encourage folks like you to maintain your overlays elsewhere.

We'll also make sure to send updates about our plans for our configuration API. It's a tough problem and we're currently focused on some higher, blocking priorities for GA.

Hope that all makes sense. Do you think it makes sense to close this issue for the time being and maybe re-open it later?

**Comment by jamespollard8** [comment]
> Do you have an example for this? Because you can basically overlay everything with YTT (not sure if I should consider this a good or bad thing though). See for an example the overlay mentioned above, it overlays the uaa configuration that the uaa writes to a ConfigMap and cf-for-k8s has already overlayed once...

I don't have an example. If you're curious to dig deeper on this, I'd recommend dropping something in the #cf-for-k8s slack channel to crowd-source a response.

**Comment by loewenstein** [comment]
@jamespollard8 Should close it in favour of an issue describing the need for (and work on) a general concept for cf-for-k8s configuration?

**Comment by jamespollard8** [comment]
> @jamespollard8 Should close it in favour of an issue describing the need for (and work on) a general concept for cf-for-k8s configuration?

Sure. The work of that general configuration concept is top-of-mind for us - we're working on it. I'd encourage people who have interest and input to start/join conversations on the #cf-for-k8s CF slack channel.

On Friday, we made some progress in this regard as captured by my message here: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1592612406136400
