### ISSUE TITLE
`cf push` fails for images from private registries

### ISSUE THREAD

**Issue by jkbschmid** [cloudfoundry/cf-for-k8s#194]
### Summary

When using a private app registry, `cf push` from a source app fails. Staging is successful, but the app does not start, because of an ImagePullBackoff.
This is because the imagePullSecret references the unversioned Secret `app-registry-credentials` instead of `app-registry-credentials-ver-X`.
```
imagePullSecrets:
    - name: app-registry-credentials
```
This is defined here: https://github.com/cloudfoundry/cf-for-k8s/blob/edd5c11449790aadffeff9a2bcd6f61f20371d55/config/_ytt_lib/eirini/rendered.yml#L157

### Possible Fix
Because the target value is 'yaml inside a yamlstring', we cannot easily add a kapp Config to automatically version the secret name. A solution would be to not version this secret at all, i.e. to always use `app-registry-credentials` without the suffix. This should not be a problem, because the secret is never stale, because it is only used during pod initialization. 
This change could be implemented by adding an exception to https://github.com/cloudfoundry/cf-for-k8s/blob/0d3f9968d71d8d399632573281ed93abbe5801bd/config/z-kapp-versioned-creds.yml.

### Reproduction Steps
https://github.com/cloudfoundry/cf-for-k8s/commit/edd5c11449790aadffeff9a2bcd6f61f20371d55

Gardener

output of `ytt --version ; kapp --version ; kubectl version`:
```
ytt version 0.27.1
kapp version 0.26.0

Succeeded
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

```
### Expected behavior

`cf push` should work.

**Comment by jkbschmid** [comment]
@acosta11

**Comment by acosta11** [comment]
Breaking change reverted in c3df58e1dc. Thank you for raising the issue!

Thanks,
Andrew

**Comment by phil9909** [comment]
I think it would make sense to simply exclude the `app-registry-credentials` form versioning. Imagine the following scenario: One rotates the gcr credentials and updates the secret, now all workloads are restarted, because the spec changed. I think that is not what we want.

If you really want to have versioned Secrets everywhere without an exception, I have the following proposal:
- Kubernetes supports tying an `imagePullSecret` to a `ServiceAccount`: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#serviceaccount-v1-core which is already supported the `kapp` default `templateRules`: https://github.com/k14s/kapp/blob/46b7b62e82f556b1090826e167040b6f4d750d08/pkg/kapp/config/default.go#L264-L266
- We could then add the `imagePullSecret` to the two `ServiceAccounts` used by eirini:  [`eirini`](https://github.com/cloudfoundry/cf-for-k8s/blob/05e1942b8c1f515c48677e33bf1a17fc0a7d8caf/build/eirini/_vendir/eirini/templates/serviceaccount.yaml#L2-L6) and [`eirini-privileged`](https://github.com/cloudfoundry/cf-for-k8s/blob/05e1942b8c1f515c48677e33bf1a17fc0a7d8caf/build/eirini/_vendir/eirini/templates/app-privileged-pod-security-policy.yaml#L2-L6)
- Additionally, we would have to remove the `imagePullSecrets` from the `StatefulSets` eirini generates (because they have precedence over the `ServiceAccount`). It might be sufficient to delete this line https://github.com/cloudfoundry/cf-for-k8s/blob/edd5c11449790aadffeff9a2bcd6f61f20371d55/config/_ytt_lib/eirini/rendered.yml#L157, but we should check with the eirini-team.

This should also prevent restarting (as the pod-spec stays the same, just the `ServiceAccount` is updated).
