### ISSUE TITLE
Image Size become huge with 0.4.0

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry/cf-for-k8s#266]
## Describe the bug

In previous releases when we push applications, the image size used to be around 32 MB. 
We deployed new 0.4.0 release version and if we push the same application we could see the image size as 420 MB. 

This is observed across all buildpacks(we tried with go, nodejs and java) . We suspect this because of new paketo buildpacks.

## To Reproduce*
1. Deploy previous release versions (0.3.0)
2. Push  [sample nodejs app](https://github.com/cloudfoundry-samples/cf-sample-app-nodejs)
3. Check the image size from registry
4. Deploy 0.4.0 release
2. Push the same application
3. check the image size

*_ snippets_*
<img src="https://user-images.githubusercontent.com/29627753/86236295-7ab03900-bbb7-11ea-8498-03fea749b86c.png" width="448">
<img src="https://user-images.githubusercontent.com/29627753/86236239-653b0f00-bbb7-11ea-82c8-871c2027cfe9.png" width="448">

## Expected behavior

Image size should not be this much huge.

### cf-for-k8s
[0.4.0](https://github.com/cloudfoundry/cf-for-k8s/releases/tag/v0.4.0)

**Comment by jamespollard8** [comment]
Thanks Kesavan - this is a fascinating repercussion of our on-going cloud native buildpack integration work. Thanks for taking the time to write such a great, detailed issue.

We'll be discussing this as a team and will come back with a more detailed response. But for now, a top of mind question here is:

what behavior do we expect now that we're without the droplets from CF-for-VMs world?

**Comment by paulcwarren** [comment]
Hi @KesavanKing, any response to @jamespollard8 question?

A little bit more context.  When we moved to 0.4.0 moved the base images for apps from "base" to "full".  

The kpack team are [aware of this](https://app.slack.com/client/T02FL4A1X/CUWG5TXB5/thread/CUWG5TXB5-1594134789.148500) and actually, we believe, this is configurable when using kpack directly.  It is an interesting question whether, or not, we expose that configurability in cf-for-k8s.  For that we will have to defer to @Syerram

**Comment by KesavanKing** [comment]
@jamespollard8 @paulcwarren ,Thanks for considering this issue and taking into discussions

Our expectation is like, for the builder it can be a full image and final image should contain only base os and the runtime. As an end user perspective, the image should be as slim as possible.

**Comment by Syerram** [comment]
We spoke to the build service team and the reason we have to use the "full" base image is because of the scripting languages (ruby, python etc) that require additional libraries that aren't available in "base".

Additionally, if the concern is storage size in the registry, most registries will reuse the stack layers. In other words, if you did 2 cf pushes, it won’t be 420mb x 2.  Historically, we have used the same larger stack to build apps in CF. 

I am going to close this for now and instead add a known issue on missing feature - allow app developers to use the desired stack via `cf push -s`

**Comment by loewenstein** [comment]
Hi @Syerram,

did you talk about buildpack specific stacks with the build services team? Is that a feature that either exists or would be considered to support in kpack? I think this would be a nice addition, allowing the buildpack authors to choose an optimal stack instead of putting the burden on the app developer to make that choice via `cf push - s`.

My concern btw would be potential attack surface rather than image size.

**Comment by bkrannich** [comment]
Hi @Syerram, @loewenstein,

Wanted to comment on this one as well.

> because of the scripting languages (ruby, python etc) that require additional libraries that aren't available in "base"

Isn't the exact case for which one would like to have an OCI layer as part of the image, ideally introduced by something like a "scripting languages requirements" buildpack?
