### ISSUE TITLE
cf run-task never finishes

### ISSUE THREAD

**Issue by paulcwarren** [cloudfoundry/cf-for-k8s#375]
## Describe the bug
`cf run-task` never finishes

## To Reproduce*
1. Push an application
2. Run `cf run-task <app-name> --command "sleep 2; echp Done;" --name test`
3. Wait more than 2 seconds and run `cf tasks` and inspect the output. 

## Expected behavior
Expect task to report SUCCEEDED but it actually reports RUNNING

### CLI versions
Tested with cf cli 7.0.2

## Additional Context
Due to this long-standing [istio/k8s bug](https://github.com/istio/istio/issues/11045) we believe that the task container does, in fact, run to completion but the istio-proxy container remains active preventing the pod from entering a finished state.  Therefore, eirini and by implication capi, believe the task is still running.

**Comment by emalm** [comment]
@mnitchev You mentioned that the Eirini team had introduced a task-completer component to work around this issue? Is that related to https://www.pivotaltracker.com/story/show/172175910?

**Comment by kauana** [comment]
Hello @paulcwarren we (cf-k8s-networking) have created a [bug](https://www.pivotaltracker.com/n/workspaces/799683) in our tracker to investigate this.

cc: @jenspinney

**Comment by mnitchev** [comment]
Hello @emalm, @paulcwarren, yes we worked around that issue as part of that story. Although not explicitly noted in the comments there, we now wait for the Pod's task container to terminate instead of waiting for the Job. It was done [in this commit here](https://github.com/cloudfoundry-incubator/eirini/commit/acaca5fbb55176c5e4cd9f56fda33b7357ad11a5) and is part of the `v1.7.0` release. I looks like [cf-for-k8s has already picked up that version](https://github.com/cloudfoundry/cf-for-k8s/commit/2f0b99bd1ec76577a803db61aba000457526c2d4). Can you make sure you're using the latest cf-for-k8s release?

**Comment by mnitchev** [comment]
Hey,

So we saw this issue in the new [0.6.0](https://github.com/cloudfoundry/cf-for-k8s/releases/tag/v0.6.0) release. It looks like we've made a mistake and the new NetworkPolicies aren't correct for the task reporter. We've also since then introduced a new [webhook that injects the CF_INSTANCE_INDEX env var](https://www.pivotaltracker.com/story/show/173150663) which also requires a NetworkPolicy. 
We have created a [bug in our tracker](#174512894) about this, and we'll create a PR to fix it.

cc @cloudfoundry/eirini

**Comment by davewalter** [comment]
Fixed by #396.
