### ISSUE TITLE
Remove loadbalancer (LB) property and related properties that enable Loadbalancer services

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#420]
## Summary
LoadBalancer is not a standard part of Kubernetes API [1]. Each IaaS and commercial K8s providers have a slightly different setup for LoadBalancer creation. To reduce the surface area and custom configurations, cf-for-k8s intends to adhere to K8s API as close as possible. 

Platform teams can configure a LoadBalancer directly with their IaaS providers and then connect the LB to the foundation [2]

[1] There is a new project in the CNCF incubator called [Porter](https://itnext.io/porter-an-open-source-load-balancer-designed-for-bare-metal-kubernetes-clusters-870e1313b7f0). Once it becomes available in core K8s API, cf-for-k8s will make load balancer as an option to configure.

[2] Issue #419 output is an install docs for the IaaS cluster. Add a note stating that we expect users to configure an IaaS load balancer and connect that to the foundation.

### Remove load-balancer related properties
**Given** that I have access to view `config/values/00-values.yml`
**Then** I notice that I cannot configure a load balancer anymore and the following properties are no longer available 

| Config Property |
| ----------- |
| `enable_load_balancer` | 
| `istio_static_ip` |

### Install on Kind
**Given** that I installed cf-for-k8s using the default configuration on kind local cluster
**When** I cf push the app to the foundation (via `vcap.me`
**Then** the app is successfully pushed and I can curl the app

## Technical notes
- This story will break RelInt GKE based CI, since it uses the load-balancer and static-ip properties. Since it is not part of the product anymore, CI should leverage overlays to inject the right values to work with GKE and other IaaSes.

**Comment by XanderStrike** [comment]
I believe the 2nd AC steps will succeed _today_ without changes, and I'm dubious of the value of the first AC. This is an issue for removing a feature and it's not clear to me why we would want to do that.

I understand that `type: LoadBalancer` doesn’t work on all IaaSes or kubernetes distributions, but neither do other things like network policy or more secure 3rd party jwt tokens that we plan to ship. Why take the option away from everyone who will benefit from it simply because it won’t work for some subset of users? Could we instead document its limitations but keep it available for our many users who will be using more capable public IaaSes? Having manually set up an LB a couple times for a gke cluster I can say it’s not a particularly fun or easy experience, and having cf-for-k8s handle it makes it a breeze.

This is a feature that is depended on heavily by almost every team's CI, so even if we accept the (so far unsubstantiated) assumption that most of our users won't be using public cloud, shouldn't we at least keep this in place to avoid breaking every team's CI a mere month before our planned 1.0? Remember, we're users too 😄

**Comment by emalm** [comment]
Yeah, +1 from me on the value of auto-provisioning an LB for the ingress gateway on infrastructures that support it. I've also found that to be convenient with GKE clusters and with PKS on GCP and vSphere with NSX-T. I do think the property names could be adjusted to be clearer and better organized (maybe `ingress_gateway.enable_load_balancer` and `ingress_gateway.static_ip` -- no reason to mention Istio as it's an implementation detail).

**Comment by paulcwarren** [comment]
Based on the feedback and the fact that, discussing this within the team, we don't see much difference between this and properties such as `add_metrics_server_components`.  Both are IaaS specific.  

However, we will rename the properties to prevent implementation details leaking up through and into our configuration interface.
