### ISSUE TITLE
CF Push fails with v6 CLI

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/cf-for-k8s#471]
Cf pushing a source-based app to the most recent commit on the `master` branch hangs when staging the app:

```
cf push test -u none -m 32M -k 100M -i 1                                                                                                                                        
Pushing app test to org system / space test as admin...
Getting app info...
Creating app with these attributes...
+ name:                test
  path:                /home/pivotal/workspace/cf-k8s-logging/examples/forwarder-golang
+ disk quota:          100M
+ health check type:   none
+ instances:           1
+ memory:              32M
  routes:
+   test.apps.corgi.loggr.cf-app.com

Creating app test...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 2.14 KiB / 2.14 KiB [========================================================================================================================================================================================================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
```

## To Reproduce*
1. `cf push` source-based app
2. push hangs forever
3. No build pods are created

## Expected behavior
CF push succeeds or fails with an `unsupported version` error

### cf-for-k8s SHA 
14b11cad112a150e1577ecc3ad90491005c8b9fe

**Comment by tcdowney** [comment]
The switch to using an OCI image registry for storing app packages is what ultimately broke the V2 APIs here (https://github.com/cloudfoundry/cf-for-k8s/pull/430).

Since we're only supporting the V3 APIs/V7 CLI with cf-for-k8s, I believe the plan is to set the `min_cli_version` (https://github.com/cloudfoundry/capi-release/blob/0c5ac87ae0d67f9eaca603b141128015d7654e33/jobs/cloud_controller_ng/spec#L397) on the CF API to be `7+` so that users get a better experience here.

cc @pivotal-mikegresham @piyalibanerjee @cwlbraa

**Comment by tcdowney** [comment]
Here's the story on our end around the min CLI version:
https://www.pivotaltracker.com/story/show/174981838

**Comment by jamespollard8** [comment]
Thanks @MasslessParticle for filing the issue.

I'm going to close this as "won't fix" because we do not plan to support the v6 cf cli for cf-for-k8s and we've documented the requirement: https://github.com/cloudfoundry/cf-for-k8s/blob/37927943380d25c63cc41c7e255327335ef7905b/docs/deploy.md#required-tools
