### ISSUE TITLE
Gateway access logs do not appear in cf log 

### ISSUE THREAD

**Issue by XanderStrike** [cloudfoundry/cf-for-k8s#520]
This appears to be a regression of https://www.pivotaltracker.com/n/projects/2407973/stories/173568724

## STR:

1. Deploy a cf-for-k8s
2. Push an app
3. Run `cf logs <appname>`
4. Curl the app

## Expected:

JSON access logs emitted by the ingressgateway appear.

## Observed:

No access logs are visible.

### cf-for-k8s SHA 
4aa12672c2727f8886b41baf020c8a97d95385c3

The cf-k8s-networking team has a bug prioritized to fix this, however it may not make it by code freeze tonight: https://www.pivotaltracker.com/story/show/175210582

**Comment by mike1808** [comment]
I suppose this can be because of the change in Istio 1.7 making gatways [to run as non-root](https://github.com/istio/istio/pull/23379) which prevent fluent-bit to mount [/var/lib/docker/containers](https://github.com/cloudfoundry/cf-for-k8s/blob/master/build/istio/overlays/add-fluent-bit-sidecar-to-ingressgateway.yaml#L50) folder from the host.

**Comment by jamespollard8** [comment]
Fixed by #521
